version: "3.9" 


services:
  web_api:
    image: 127.0.0.1:5000/web_api
    build: .
    restart: "always"
    environment:
      DBNAME: "house_data"
      DEBUG: "True"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SECRET_KEY
    ports:
      - "10000:8000"
    networks:
      - net
    depends_on:
      - worker

  worker:
    image: 127.0.0.1:5000/worker
    build: .
    entrypoint: celery
    command: "--app=app.celery worker --loglevel=info --concurrency=4"
    restart: "always"
    environment:
      DBNAME: "house_data"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SECRET_KEY
    networks:
      - net
    depends_on:
      - rabbit_mq
      - redis

  rabbit_mq:
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/RABBITMQ_DEFAULT_PASS
    secrets:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    networks:
      - net

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 300 1
    volumes: 
      - cache:/data
    networks:
      - net

volumes:
  pgadmin-data:
  cache:

networks:
  net:

secrets:
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_HOST:
    external: true
  MONGO_HOST:
    external: true
  MONGO_USERNAME:
    external: true
  MONGO_PASSWORD:
    external: true
  CELERY_BROKER_URL:
    external: true
  CELERY_RESULT_BACKEND:
    external: true
  SECRET_KEY:
    external: true
  RABBITMQ_DEFAULT_USER:
    external: true
  RABBITMQ_DEFAULT_PASS:
    external: true